In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

y=np.array([78.5,74.3,104.3,87.6,95.9,109.2,102.7,72.5,93.1,115.9,83.8,113.3,109.4])
x1=np.array([7,1,11,11,7,11,3,1,2,21,1,11,10])
x2=np.array([26,29,56,31,52,55,71,31,54,47,40,66,68])
x3=np.array([6,15,8,8,6,9,17,22,18,4,23,9,8])
x4=np.array([60,52,20,47,33,22,6,44,22,26,34,12,12])

dic={"y":y,"x1":x1,"x2":x2,"x3":x3,"x4":x4}
df=pd.DataFrame(dic)
df

,y,x1,x2,x3,x4
0,78.5,7,26,6,60
1,74.3,1,29,15,52
2,104.3,11,56,8,20
3,87.6,11,31,8,47
4,95.9,7,52,6,33
5,109.2,11,55,9,22
6,102.7,3,71,17,6
7,72.5,1,31,22,44
8,93.1,2,54,18,22
9,115.9,21,47,4,26


In [18]:
import numpy as np

# Calculate the regression coefficients (beta) using the normal equation:
# beta = (X'X)^-1 * X' * y

# Step 1: Multiply (X'X)^-1 by X'
intermediate_product = np.dot(inverse_product_XT_X, X_with_intercept_T)

# Step 2: Multiply the result by y
beta_coefficients = np.dot(intermediate_product, y_vector)

print("Regression Coefficients (beta):")
print(beta_coefficients)
print(f"Shape of beta_coefficients: {beta_coefficients.shape}")

Regression Coefficients (beta):
[[62.4053693 ]
 [ 1.55110265]
 [ 0.51016758]
 [ 0.1019094 ]
 [-0.14406103]]
Shape of beta_coefficients: (5, 1)


In [19]:
import numpy as np

# Extract the independent variables (x1, x2, x3, x4) from the DataFrame
X = df[['x1', 'x2', 'x3', 'x4']].values

# Create a column of ones with the same number of rows as X
ones = np.ones((X.shape[0], 1))

# Concatenate the column of ones with the X matrix
X_with_intercept = np.concatenate((ones, X), axis=1)

print("Original X matrix (first 5 rows):")
print(X[:5])
print("\nMatrix with first column replaced by ones (first 5 rows):")
print(X_with_intercept[:5])

Original X matrix (first 5 rows):
[[ 7 26  6 60]
 [ 1 29 15 52]
 [11 56  8 20]
 [11 31  8 47]
 [ 7 52  6 33]]

Matrix with first column replaced by ones (first 5 rows):
[[ 1.  7. 26.  6. 60.]
 [ 1.  1. 29. 15. 52.]
 [ 1. 11. 56.  8. 20.]
 [ 1. 11. 31.  8. 47.]
 [ 1.  7. 52.  6. 33.]]


In [20]:
# Extract the 'y' column from the DataFrame
y_column = df['y'].values

# Reshape the 1D array into a column vector
y_vector = y_column.reshape(-1, 1)

print("Original 'y' values (first 5 elements):")
print(y_column[:5])
print("\n'y' column as a vector (first 5 elements and shape):")
print(y_vector[:5])
print(f"Shape of y_vector: {y_vector.shape}")

Original 'y' values (first 5 elements):
[ 78.5  74.3 104.3  87.6  95.9]

'y' column as a vector (first 5 elements and shape):
[[ 78.5]
 [ 74.3]
 [104.3]
 [ 87.6]
 [ 95.9]]
Shape of y_vector: (13, 1)


In [21]:
# Calculate the transpose of X_with_intercept
X_with_intercept_T = X_with_intercept.T

print("Transpose of X_with_intercept matrix:")
print(X_with_intercept_T)

Transpose of X_with_intercept matrix:
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 7.  1. 11. 11.  7. 11.  3.  1.  2. 21.  1. 11. 10.]
 [26. 29. 56. 31. 52. 55. 71. 31. 54. 47. 40. 66. 68.]
 [ 6. 15.  8.  8.  6.  9. 17. 22. 18.  4. 23.  9.  8.]
 [60. 52. 20. 47. 33. 22.  6. 44. 22. 26. 34. 12. 12.]]


In [22]:
# Perform matrix multiplication: X_with_intercept_T * X_with_intercept
product_XT_X = np.dot(X_with_intercept_T, X_with_intercept)

print("Result of (X_with_intercept_T * X_with_intercept):")
print(product_XT_X)
print(f"Shape of the resulting matrix: {product_XT_X.shape}")

Result of (X_with_intercept_T * X_with_intercept):
[[1.3000e+01 9.7000e+01 6.2600e+02 1.5300e+02 3.9000e+02]
 [9.7000e+01 1.1390e+03 4.9220e+03 7.6900e+02 2.6200e+03]
 [6.2600e+02 4.9220e+03 3.3050e+04 7.2010e+03 1.5739e+04]
 [1.5300e+02 7.6900e+02 7.2010e+03 2.2930e+03 4.6280e+03]
 [3.9000e+02 2.6200e+03 1.5739e+04 4.6280e+03 1.5062e+04]]
Shape of the resulting matrix: (5, 5)


In [23]:
# Calculate the inverse of product_XT_X
inverse_product_XT_X = np.linalg.inv(product_XT_X)

print("Inverse of (X_with_intercept_T * X_with_intercept):")
print(inverse_product_XT_X)
print(f"Shape of the inverse matrix: {inverse_product_XT_X.shape}")

Inverse of (X_with_intercept_T * X_with_intercept):
[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]
Shape of the inverse matrix: (5, 5)


In [24]:
import numpy as np

# Calculate the regression coefficients (beta) using the normal equation:
# beta = (X'X)^-1 * X' * y

# Step 1: Multiply (X'X)^-1 by X'
intermediate_product = np.dot(inverse_product_XT_X, X_with_intercept_T)

# Step 2: Multiply the result by y
beta_coefficients = np.dot(intermediate_product, y_vector)

print("Regression Coefficients (beta):")
print(beta_coefficients)
print(f"Shape of beta_coefficients: {beta_coefficients.shape}")

Regression Coefficients (beta):
[[62.4053693 ]
 [ 1.55110265]
 [ 0.51016758]
 [ 0.1019094 ]
 [-0.14406103]]
Shape of beta_coefficients: (5, 1)


In [25]:
# Calculate the inverse of product_XT_X
inverse_product_XT_X = np.linalg.inv(product_XT_X)

print("Inverse of (X_with_intercept_T * X_with_intercept):")
print(inverse_product_XT_X)
print(f"Shape of the inverse matrix: {inverse_product_XT_X.shape}")

Inverse of (X_with_intercept_T * X_with_intercept):
[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]
Shape of the inverse matrix: (5, 5)


In [26]:
# Perform matrix multiplication: X_with_intercept_T * X_with_intercept
product_XT_X = np.dot(X_with_intercept_T, X_with_intercept)

print("Result of (X_with_intercept_T * X_with_intercept):")
print(product_XT_X)
print(f"Shape of the resulting matrix: {product_XT_X.shape}")

Result of (X_with_intercept_T * X_with_intercept):
[[1.3000e+01 9.7000e+01 6.2600e+02 1.5300e+02 3.9000e+02]
 [9.7000e+01 1.1390e+03 4.9220e+03 7.6900e+02 2.6200e+03]
 [6.2600e+02 4.9220e+03 3.3050e+04 7.2010e+03 1.5739e+04]
 [1.5300e+02 7.6900e+02 7.2010e+03 2.2930e+03 4.6280e+03]
 [3.9000e+02 2.6200e+03 1.5739e+04 4.6280e+03 1.5062e+04]]
Shape of the resulting matrix: (5, 5)


In [27]:
# Extract the 'y' column from the DataFrame
y_column = df['y'].values

# Reshape the 1D array into a column vector
y_vector = y_column.reshape(-1, 1)

print("Original 'y' values (first 5 elements):")
print(y_column[:5])
print("\n'y' column as a vector (first 5 elements and shape):")
print(y_vector[:5])
print(f"Shape of y_vector: {y_vector.shape}")

Original 'y' values (first 5 elements):
[ 78.5  74.3 104.3  87.6  95.9]

'y' column as a vector (first 5 elements and shape):
[[ 78.5]
 [ 74.3]
 [104.3]
 [ 87.6]
 [ 95.9]]
Shape of y_vector: (13, 1)


In [28]:
# Calculate the transpose of X_with_intercept
X_with_intercept_T = X_with_intercept.T

print("Transpose of X_with_intercept matrix:")
print(X_with_intercept_T)

Transpose of X_with_intercept matrix:
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 7.  1. 11. 11.  7. 11.  3.  1.  2. 21.  1. 11. 10.]
 [26. 29. 56. 31. 52. 55. 71. 31. 54. 47. 40. 66. 68.]
 [ 6. 15.  8.  8.  6.  9. 17. 22. 18.  4. 23.  9.  8.]
 [60. 52. 20. 47. 33. 22.  6. 44. 22. 26. 34. 12. 12.]]


In [29]:
import numpy as np

# Extract the independent variables (x1, x2, x3, x4) from the DataFrame
X = df[['x1', 'x2', 'x3', 'x4']].values

# Create a column of ones with the same number of rows as X
ones = np.ones((X.shape[0], 1))

# Concatenate the column of ones with the X matrix
X_with_intercept = np.concatenate((ones, X), axis=1)

print("Original X matrix (first 5 rows):")
print(X[:5])
print("\nMatrix with first column replaced by ones (first 5 rows):")
print(X_with_intercept[:5])

Original X matrix (first 5 rows):
[[ 7 26  6 60]
 [ 1 29 15 52]
 [11 56  8 20]
 [11 31  8 47]
 [ 7 52  6 33]]

Matrix with first column replaced by ones (first 5 rows):
[[ 1.  7. 26.  6. 60.]
 [ 1.  1. 29. 15. 52.]
 [ 1. 11. 56.  8. 20.]
 [ 1. 11. 31.  8. 47.]
 [ 1.  7. 52.  6. 33.]]
